name: .NET Core Desktop

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: windows-latest 
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .net
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x        
    - name: restore dependencies
      run : dotnet restore
    
    - name: package build
      run : dotnet build -c Release -o out
    
    - name: Nuget push
      run: |
            cd out
            dotnet nuget push *.nupkg --api-key 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 --source "https://nuget.pkg.github.com/wellmac/index.json --skip-duplicate
